# Generated by Django 3.0.5 on 2020-05-01 02:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('collaborator', '0001_initial'),
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='eventoredzone',
            old_name='portalName',
            new_name='portal',
        ),
        migrations.AddField(
            model_name='eventoredzone',
            name='collaborator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='collaborator.Collaborator'),
        ),
    ]
