# Generated by Django 3.0.5 on 2022-05-04 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20200430_2348'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventoCore',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('type_event', models.CharField(max_length=6)),
                ('id_event', models.CharField(max_length=10)),
                ('code', models.CharField(max_length=6)),
                ('data', models.CharField(max_length=17)),
                ('date', models.DateTimeField()),
            ],
        ),
    ]
