# Generated by Django 3.0.5 on 2022-05-04 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tag', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TagCore',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('description', models.CharField(blank=True, max_length=50, null=True)),
                ('uuid', models.CharField(max_length=15)),
                ('temperature', models.IntegerField()),
                ('battery', models.IntegerField(blank=True, null=True)),
                ('statusAssociacao', models.IntegerField(blank=True, null=True)),
                ('dateCreate', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
