# Generated by Django 3.0.5 on 2022-05-04 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tag', '0002_tagcore'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tagcore',
            name='dateCreate',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
