# Generated by Django 3.0.5 on 2022-05-04 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tag', '0003_auto_20220504_1833'),
    ]

    operations = [
        migrations.AddField(
            model_name='tagcore',
            name='dateUpdate',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
