# Generated by Django 3.0.5 on 2022-05-05 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tag', '0004_tagcore_dateupdate'),
    ]

    operations = [
        migrations.AddField(
            model_name='tagcore',
            name='status',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
